#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
const
  _libcrash =
    require(
      'crash-js');
/* global
     _path_join */
/* eslint-disable-next-line
     no-native-reassign */
_path_join =
  _libcrash._path_join;
const
  _evm_chains_info_module =
    require(
      'evm-chains-info');
/* global
     _evm_chains_db_path_get */
/* eslint-disable-next-line
     no-native-reassign */
_evm_chains_db_path_get =
  _evm_chains_info_module._evm_chains_db_path_get;
/* global
     _rpc_backend_get */
/* eslint-disable-next-line
     no-native-reassign */
_rpc_backend_get =
  _evm_chains_info_module._rpc_backend_get;
/* global
     _evm_chain_info_get */
/* eslint-disable-next-line
     no-native-reassign */
_evm_chain_info_get =
  _evm_chains_info_module._evm_chain_info_get;

function
  _contract_abi_get(
    _deployments_dir,
    _contract_name,
    _network_chain_id,
    _version) {
  const
    _file_name =
      _contract_name.concat(
        ".abi.json");
  const
    _path =
      _path_join(
        [_deployments_dir,
         _contract_name,
         _network_chain_id,
         _version,
         _file_name]);
  return _path;
}

function
  _contract_bytecode_get(
    _deployments_dir,
    _contract_name,
    _network_chain_id,
    _version) {
  const
    _file_name =
      _contract_name.concat(
        ".bin");
  const
    _path =
      _path_join(
        [_deployments_dir,
         _contract_name,
         _network_chain_id,
         _version,
         _file_name]);
  return _path;
}

function
  _contract_compiler_output_get(
    _deployments_dir,
    _contract_name,
    _network_chain_id,
    _version) {
  const
    _file_name =
      _contract_name.concat(
        ".json");
  const
    _path =
      _path_join(
        [_deployments_dir,
         _contract_name,
         _network_chain_id,
         _version,
         _file_name]);
  return _path;
}

function
  _libevm_cmdline_parse(
    _argv) {
  if ( "w" in _argv ) {
    /* global
         wallet_path */
    /* eslint-disable-next-line
         no-native-reassign */
    wallet_path =
      _argv[
        "w"];
  }
  if ( "wallet-path" in _argv ) {
    wallet_path =
      _argv[
        "wallet-path"];
  }
  if ( "p" in _argv ) {
    /* global
         wallet_password */
    /* eslint-disable-next-line
         no-native-reassign */
    wallet_password =
      _argv[
        "p"];
  }
  if ( "wallet-password" in _argv ) {
    wallet_path =
      _argv[
        "wallet-password"];
  }
  if ( "s" in _argv ) {
    /* global
         wallet_seed */
    /* eslint-disable-next-line
         no-native-reassign */
    wallet_seed =
      _argv[
        "s"];
  }
  if ( "wallet-seed" in _argv ) {
    wallet_seed =
      _argv[
        "wallet-seed"];
  }
  if ( "k" in _argv ) {
    /* global
         api_key */
    /* eslint-disable-next-line
         no-native-reassign */
    api_key =
      _argv[
        "k"];
  }
  if ( "api-key" in _argv ) {
    api_key =
      _argv[
        "api-key"];
  }
  if ( "n" in _argv ) {
    /* global
         target_networks */
    target_networks.push(
      _argv[
        "n"]);
  }
  if ( "network" in _argv ) {
    target_networks.push(
      _argv[
        "network"]);
  }
}

module.exports = {
  _contract_abi_get:
    _contract_abi_get,
  _contract_bytecode_get:
    _contract_bytecode_get,
  _contract_compiler_output_get:
    _contract_compiler_output_get,
  _evm_chains_db_path_get:
    _evm_chains_db_path_get,
  _evm_chain_info_get:
    _evm_chain_info_get,
  _libevm_cmdline_parse:
    _libevm_cmdline_parse,
  _rpc_backend_get:
    _rpc_backend_get
};
