#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
const
  _libcrash =
    require(
      'crash-js');
/* global
     _homedir_get */
/* eslint-disable-next-line
     no-global-assign */
_homedir_get =
  _libcrash._homedir_get;
/* global
     _msg_info */
/* eslint-disable-next-line
     no-global-assign */
_msg_info =
  _libcrash._msg_info;
/* global
     _path_join */
/* eslint-disable-next-line
     no-global-assign */
_path_join =
  _libcrash._path_join;
const
  _evm_chains_info_module =
    require(
      'evm-chains-info');
/* global
     _evm_chains_db_path_get */
/* eslint-disable-next-line
     no-global-assign */
_evm_chains_db_path_get =
  _evm_chains_info_module._evm_chains_db_path_get;
/* global
     _rpc_backend_get */
/* eslint-disable-next-line
     no-global-assign */
_rpc_backend_get =
  _evm_chains_info_module._rpc_backend_get;
/* global
     _evm_chain_info_get */
/* eslint-disable-next-line
     no-global-assign */
_evm_chain_info_get =
  _evm_chains_info_module._evm_chain_info_get;
const
  _evm_wallet_module =
    require(
      "evm-wallet.js");
const
  _address_get =
    _evm_wallet_module._address_get;

function
  _libevm_global_variables() {
  /* global
       call_auth:
         writable */
  call_auth =
    "";
  /* global
       wallet_name:
         writable */
  wallet_name =
    "";
  /* global
       wallet_path:
         writable */
  wallet_path =
    "";
  /* global
       wallet_password:
         writable */
  wallet_password =
    "";
  /* global
       wallet_address:
         writable */
  wallet_address =
    "";
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       api_key:
         writable */
  api_key =
    "";
  /* global
       networks_amount:
         writable */
  networks_amount =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       target_networks:
         writable */
  target_networks =
    [];
  /* global
       rpc_selection:
         writable */
  rpc_selection =
    "";
  /* global
       retries_max:
         writable */
  retries_max =
    "";
  /* global
       call_timeout:
         writable */
  call_timeout =
    "";
  /* global
       msg_value:
         writable */
  msg_value =
    "";
}

function
  _libevm_app_global_variables() {
  /* global
       deployments_dir:
         writable */
  deployments_dir =
    "";
  /* global
       user_level:
         writable */
  user_level =
    "";
}

function
  _contract_abi_get(
    _deployments_dir,
    _contract_name,
    _network_chain_id,
    _version) {
  const
    _file_name =
      _contract_name.concat(
        ".abi.json");
  const
    _path =
      _path_join( [
        _deployments_dir,
        _contract_name,
        _network_chain_id,
        _version,
        _file_name
      ]);
  return _path;
}

function
  _contract_bytecode_get(
    _deployments_dir,
    _contract_name,
    _network_chain_id,
    _version) {
  const
    _file_name =
      _contract_name.concat(
        ".bin");
  const
    _path =
      _path_join(
        [_deployments_dir,
         _contract_name,
         _network_chain_id,
         _version,
         _file_name]);
  return _path;
}

function
  _contract_compiler_output_get(
    _deployments_dir,
    _contract_name,
    _network_chain_id,
    _version) {
  const
    _file_name =
      _contract_name.concat(
        ".json");
  const
    _path =
      _path_join(
        [_deployments_dir,
         _contract_name,
         _network_chain_id,
         _version,
         _file_name]);
  return _path;
}

function
  _wallet_path_get(
    _wallet_app,
    _wallet_name,
    _qr_support) {
  let
    _wallet_dir;
  if ( typeof(
         _wallet_app) == "undefined" ||
       _wallet_app == "" ) {
    _wallet_app =
      "evm-wallet";
  }
  if ( typeof(
         _wallet_name) == "undefined" ||
       _wallet_name == "" ) {
    _wallet_name =
      "default";
  }
  if ( typeof(
         _qr_support) == "undefined" ||
       _qr_support == "" ) {
    _qr_support =
      "n";
  }
  const
    _home =
      _homedir_get();
  _wallet_dir =
    _path_join( [
      _home,
      ".config",
      _wallet_app ]);
  if ( _qr_support == "y" ) {
    _wallet_dir =
      _path_join( [
        _wallet_dir,
        "qr" ]);
  }
  const
    _path =
      _path_join( [
        _wallet_dir,
        `${_wallet_name}.dat` ]);
  return _path;
}

function
  _secret_path_get(
    _secret,
    _app,
    _wallet_name,
    _qr){
  if ( typeof(
         _secret) == "undefined" ||
       _secret == "" ) {
    _secret =
      "seed";
  }
  if ( typeof(
         _app) == "undefined" ||
       _app == "" ) {
    _app =
      "evm-wallet";
  }
  if ( typeof(
         _wallet_name) == "undefined" ||
       _wallet_name == "" ) {
    _wallet_name =
      "default";
  }
  if ( typeof(
         _qr_support) == "undefined" ||
       _qr_support == "" ) {
    _qr_support =
      "n";
  }
  const
    _config_dir =
      _path_join( [
        _homedir_get(),
        ".config",
        _app ]);
  if ( _qr_support == "y" ) {
    _config_dir =
      _path_join( [
        _config_dir,
        "qr" ]);
  }
  const
    _secret_path =
      _path_join( [
        _config_dir,
        `${_wallet_name}-${_secret}.txt` ]);
  return _secret_path;
}

function
  _secret_get(
    _secret,
    _secret_type,
    _wallet_app,
    _wallet_name,
    _qr_support) {
  if ( typeof(
         _secret) == "undefined" ||
       _secret == "" ) {
    _secret =
      "seed";
  }
  if ( typeof(
         _secret) == "undefined" ||
       _secret == "" ) {
    _secret_type =
      "seed";
  }
  if ( typeof(
         _wallet_app) == "undefined" ||
       _wallet_app == "" ) {
    _wallet_app =
      "evm-wallet";
  }
  if ( typeof(
         _wallet_name) == "undefined" ||
       _wallet_name == "" ) {
    _wallet_name =
      "default";
  }
  if ( typeof(
         _qr_support) == "undefined" ||
       _qr_support == "" ) {
    _qr_support =
      "n";
  }
  _secret_path =
    _secret_path_get(
      _secret,
      _wallet_app,
      _wallet_name,
      _qr_support);
  return _secret_path;
}

function
  _libevm_cmdline_parse(
    _argv) {
  if ( "N" in _argv ) {
    wallet_name =
      _argv[
        "N"];
  }
  if ( "wallet-name" in _argv ) {
    wallet_name =
      _argv[
        "wallet-name"];
  }
  if ( "w" in _argv ) {
    wallet_path =
      _argv[
        "w"];
  }
  if ( "wallet-path" in _argv ) {
    wallet_path =
      _argv[
        "wallet-path"];
  }
  if ( "p" in _argv ) {
    wallet_password =
      _argv[
        "p"];
  }
  if ( "wallet-password" in _argv ) {
    wallet_path =
      _argv[
        "wallet-password"];
  }
  if ( "s" in _argv ) {
    wallet_seed =
      _argv[
        "s"];
  }
  if ( "wallet-seed" in _argv ) {
    wallet_seed =
      _argv[
        "wallet-seed"];
  }
  if ( "k" in _argv ) {
    api_key =
      _argv[
        "k"];
  }
  if ( "api-key" in _argv ) {
    api_key =
      _argv[
        "api-key"];
  }
  if ( "n" in _argv ) {
    target_networks.push(
      _argv[
        "n"]);
  }
  if ( "network" in _argv ) {
    target_networks.push(
      _argv[
        "network"]);
  }
}

function
  _libevm_url_parse() {
  /* global
       _argv_url_get */
  wallet_path =
    _argv_url_get(
      "wallet_path")[
        0];
  wallet_password =
    _argv_url_get(
      "wallet_password")[
        0];
  wallet_seed =
    _argv_url_get(
      "wallet_seed")[
        0];
  api_key =
    _argv_url_get(
      "api_key")[
        0];
  target_networks.push(
    _argv_url_get(
      "network")[
        0]);
}

function
  _libevm_app_cmdline_parse(
    _argv) {
  if ( "u" in _argv ) {
    user_level =
      _argv[
        "u"];
  }
  if ( "user-level" in _argv ) {
    user_level =
      _argv[
        "user_level"];
  }
  if ( "d" in _argv ) {
    deployments_dir =
      _argv[
        "d"];
  }
  if ( "deployments-dir" in _argv ) {
    deployments_dir =
      _argv[
        "deployments_dir"];
  }
}

function
  _libevm_app_url_parse() {
  user_level =
    _argv_url_get(
      "user_level")[
        0];
  deployments_dir =
    _argv_url_get(
      "deployments_dir")[
        0];
}

async function
  _wallet_overrides_set(
    _wallet_app,
    _wallet_name,
    _call_auth,
    _qr_support) {
  let
    _msg,
    _wallet_address,
    _wallet_seed,
    _wallet_password,
    _wallet_path;
  /* eslint-disable
       prefer-const  */
  _wallet_seed =
    "";
  if ( typeof(
         _wallet_app) == "undefined" ||
       _wallet_app == "" ) {
      _wallet_app =
        "evm-wallet";
  }
  if ( typeof(
         _wallet_name) == "undefined" ||
       _wallet_name == "" ) {
      _wallet_name =
        "default";
  }
  if ( typeof(
         _call_auth) == "undefined" ||
       _call_auth == "" ) {
      _call_auth =
        "y";
  }
  if ( typeof(
         _qr_support) == "undefined" ||
       _qr_support == "" ) {
      _qr_support =
        "n";
  }
  _wallet_address =
    "";
  _msg =
    "Getting default wallets credentials paths for " +
    `app '${_wallet_app}' and wallet '${_wallet_name}'.`;
  _msg_info(
    _msg);
  if ( _call_auth == "y" ) {
    // undefined
    _wallet_path =
      _wallet_path_get(
        _wallet_app,
        _wallet_name,
        _qr_support);
    _wallet_seed =
      _secret_get(
        "seed",
        "seed",
        _wallet_app,
        _wallet_name,
        _qr_support);
    _msg =
      `Wallet seed: '${_wallet_seed}'`;
    _msg_info(
      _msg);
    _wallet_password =
      _secret_get(
        "password",
        "plain",
        _wallet_app,
        _wallet_name,
        _qr_support);
    console.log(
      "hello");
    await _address_get(
      _wallet_seed,
      "",             // _target_network,
      "",             // _api_key,
      "",             // _chain_id,
      "",             // _chain_name,
      "",             // _output_file
    );
    _wallet_address = 
       await _address_get(
         _wallet_seed,
         "",             // _target_network,
         "",             // _api_key,
         "",             // _chain_id,
         "",             // _chain_name,
         "",             // _output_file
       );
    // to be turned into _msg_debug
    _msg =
      `Wallet address: '${_wallet_address}'`;
    _msg_info(
      _msg);
  }
  else if ( _call_auth == "n" ) {
    if ( typeof(
           wallet_seed) == "undefined" ) {
      wallet_seed =
        "";
    }
    if ( typeof(
           wallet_password) == "undefined" ) {
      wallet_password =
        "";
    }
  }
  if ( typeof(
         wallet_name) == "undefined" ||
       wallet_name == "" ) {
    wallet_name =
      _wallet_name;
  }
  if ( typeof(
         wallet_path) == "undefined" ||
       wallet_path == "" ) {
    wallet_path =
      _wallet_path;
  }
  if ( typeof(
         wallet_address) == "undefined" ||
       wallet_address == "" ) {
    wallet_address =
      _wallet_address;
  }
  return true;
}

module.exports = {
  _contract_abi_get:
    _contract_abi_get,
  _contract_bytecode_get:
    _contract_bytecode_get,
  _contract_compiler_output_get:
    _contract_compiler_output_get,
  _evm_chains_db_path_get:
    _evm_chains_db_path_get,
  _evm_chain_info_get:
    _evm_chain_info_get,
  _libevm_app_cmdline_parse:
    _libevm_app_cmdline_parse,
  _libevm_cmdline_parse:
    _libevm_cmdline_parse,
  _libevm_app_global_variables:
    _libevm_app_global_variables,
  _libevm_global_variables:
    _libevm_global_variables,
  _libevm_url_parse:
    _libevm_url_parse,
  _rpc_backend_get:
    _rpc_backend_get,
  _wallet_overrides_set:
    _wallet_overrides_set
};
